import json
import datetime

DATA_FILE = "msms.json"
app_data = {} #This global dictionary will hold ALL our data.

# File managemnt
def load_data(path = DATA_FILE):
    """Loads all application data from a JSON file."""
    global app_data
    try:
        with open(path, 'r') as f:
            app_data = json.load(f)
            print("data loaded successfully. ")
    except FileNotFoundError:
        print("Data file not found. Initializing with default structure.")
        #if the file can't be found or doesn't exist, it will automatically create a default dictianory
        #As the dictionary to store datas of teachers and students should have keys like "students", "teachers", "attendence"
        #"next_student_id" and "next_teacher_id" should be included as well but start at 1. 
        app_data = {
            "students": [],
            "teachers": [],
            "attendance":[],
            "next_student_id": 1,
            "next_teacher_id": 1
        }

def save_data(path=DATA_FILE):
    """A function to save all aplication data to a JSON file"""
    with open(path,'w') as f:
        json.dump(app_data, f, indent=4) #Use json.dump to write the data to the file ("indent=4 is used to improve the file readability")
    print("Data saved successfully.")

#Check validity
def check_student_name(name):
    """An accessibility to check whether the student name is in the database"""
    for student in app_data["students"]:
        if name.lower() in student["name"].lower():
            return student
    return False

def check_teacher_name(name):
    """An accessibility to check whether the teacher name is in the database"""
    for teacher in app_data["teachers"]:
        if name.lower() in teacher["name"].lower():
            return teacher
    return False

def check_student_id(id):
    """An accessibility to check whether the teacher name is in the database"""
    for student in app_data['students']:
        if str(id) in str(student['id']):
            return student #If it is found then store it 
    return False

def check_teacher_id(id):
    for teacher in app_data['teachers']:
        if str(id) in str(teacher['id']):
            return teacher #If it is found then store it
    return False

def check_password(password):
    """For teacher to enter admin only features"""
    correct_password = "1234567"
    print("Please enter passcode to verify your identity")
    if password == correct_password:
        print("Core: Correct Password!")
        return True
    print("Incorrect Password!")
    return False

def check_student_password(password):
    """For student and teacher to enter particular features"""
    student_password = "7654321" #as student is limited to entering admin only features
    teacher_password = "1234567" 
    if password == student_password or password == teacher_password:
        print("Core: Correct Password!")
        return True
    print("Incorrect Password!")
    return False

#Core functions of the MSMS
def add_teacher(name, specialty):
    """Adds a teacher dictionary to the data store."""
    teacher_id = app_data["next_teacher_id"]
    new_teacher = {"id": teacher_id, "name": name, "specialty": specialty}
    app_data['teachers'].append(new_teacher)
    app_data['next_teacher_id'] += 1 #Since teacher id is auto generated by the system
    print(f"Core: Teacher '{name}' added.")

def register_student(name, instrument):
    """Register a new student into the global dictionary"""
    student_id = app_data["next_student_id"]
    enrolment = [instrument]
    new_student = {"id": student_id, "name": name, "enrolled_in": enrolment}
    app_data["students"].append(new_student)
    app_data["next_student_id"] += 1
    print(f"Core: New Student {name} ID: {student_id} enrolled in: {instrument} is registered")

def update_teacher(teacher_id, **fields):
    """Finds a teacher by ID and updates their data with provided fields"""
    for teacher in app_data["teachers"]:
        if str(teacher["id"]) == str(teacher_id):
            teacher.update(fields) 
            print(f"Teacher {teacher_id} updated.")
            return
    print(f"Error: Teacher with ID {teacher_id} not found.")

def update_student(student_id, **fields):
    """Finds a student by ID and updates their data with provided fileds"""
    for student in app_data['students']:
        if str(student["id"]) == str(student_id):
            student.update(fields)
            print(f"Student {student_id} updated.")
            return
    print(f"Student with ID {student_id} not found.")

def remove_teacher(teacher_id):
    """Removes a teacher from the data store."""
    for teacher in app_data["teachers"]:
        if str(teacher['id']) == str(teacher_id):
            app_data['teachers'].remove(teacher)
            print(f"The teacher with {teacher_id} is removed")
            return
    print(f"Error: Teacher with ID {teacher_id} not found")

def remove_student(student_id):
    """Removes a student from the data store."""
    before_remove_length = len(app_data["students"])
    app_data['students'] = [s for s in app_data["students"] if str(s['id']) != str(student_id)]
    # By using a different way as removing teacher to remove a student
    # Only the student id is not match will be added in the new data store since the matched one will be removed
    if len(app_data["students"]) < before_remove_length:
        print(f"The student with {student_id} is removed")
    else:    
        print(f"Error: Student with ID {student_id} not found")

# Receptionist features
def check_in(student_id, course_id, timestamp=None):
    """Records a student's attendance for a course."""
    if timestamp is None:
        timestamp = datetime.datetime.now().isoformat()
    if check_student_id(student_id):
        check_in_record = {
            "student_id": student_id,
            "course_id": course_id,
            "timestamp": timestamp
        }
        
        app_data['attendance'].append(check_in_record)
        print(f"Receptionist: Student {student_id} checked into {course_id}.")
        return
    print(f"Student with ID {student_id} not found")

def print_student_card(student_id):
    """Creates a text file badge for a student."""
    student_to_print = None
    for s in app_data['students']:
        if str(s['id']) == str(student_id):
            student_to_print = s
            break #To stop the loop while the student is found
    
    if student_to_print:
        filename = f"{student_id}_card.txt"
        # Open the file and overwrite it
        with open(filename, 'w') as f:
            f.write("========================\n")
            f.write(f"  MUSIC SCHOOL ID BADGE\n")
            f.write("========================\n")
            f.write(f"ID: {student_to_print['id']}\n")
            f.write(f"Name: {student_to_print['name']}\n")
            f.write(f"Enrolled In: {', '.join(student_to_print.get('enrolled_in', []))}\n")
        print(f"Printed student card to {filename}.")
    else:
        print(f"Error: Could not print card, student {student_id} not found.")

#Lookup Features

def find_student(term):
    """To search a student with any term of the student"""
    if str(term).isdigit(): #Determine wether the enter is ID
        print(f"\n--- Finding Student ID matching '{term}' ---")
        student = check_student_id(term)
        if student:
            print("Core: Student Found")
            print(f"Name: {student['name']} ID: {student['id']} Enrolled in: {student['enrolled_in']}")
            return
    elif str(term).isalpha(): # If not, then determine wether the enter is valid
        print(f"\n--- Finding Student matching '{term}' ---")
        student = check_student_name(term)
        if student:
            print("Core: Student Found")
            print(f"Name: {student['name']} ID: {student['id']} Enrolled in: {student['enrolled_in']}")
            return
    print(f"Error: Student with term {term} not found")

def find_teacher(term):
    """To search teacher with any term of the teacher"""
    if str(term).isdigit():
        print(f"\n--- Finding Teacher ID matching '{term}' ---")
        teacher = check_teacher_id(term)
        if teacher:
            print("Core: Teacher Found")
            print(f"Name: {teacher['name']} ID: {teacher['id']} Speciality: {teacher['specialty']}")
            return
    elif str(term).isalpha():
        print(f"\n--- Finding Teacher matching '{term}' ---")
        teacher = check_teacher_name(term)
        if teacher:
            print("Core: Teacher Found")
            print(f"Name: {teacher['name']} ID: {teacher['id']} Speciality: {teacher['specialty']}")
            return
    print(f"Error: Teacher with term {term} not found")

#Listing Features
def list_teachers():
    """Listing teachers recorded"""
    print("\n---- Teacher List ----")
    
    if len(app_data['teachers']) == 0:
        print("No teacher is recorded in the system.")
        return

    max_name_len = max(len(t['name']) for t in app_data['teachers'])
    max_specialty_len = max(len(t['specialty']) for t in app_data['teachers'])

    print(f"\n{'Name':<{max_name_len+2}}{'ID':<8}{'Specialty':<{max_specialty_len+2}}")
    print("-" * (max_name_len + 2 + 8 + max_specialty_len + 2))

    for teacher in app_data['teachers']:
        print(f"{teacher['name']:<{max_name_len+2}}{teacher['id']:<8}{teacher['specialty']:<{max_specialty_len+2}}")

def list_students():
    """Listing teachers recorded"""
    print("\n---- Student List ----")
    
    if len(app_data['students']) == 0:
        print("No student is recorded in the system.")
        return

    max_name_len = max(len(s['name']) for s in app_data['students'])
    max_enrolment_len = max(len(", ".join(s['enrolled_in'])) for s in app_data['students'])

    print(f"\n{'Name':<{max_name_len+2}}{'ID':<8}{'Specialty':<{max_enrolment_len+2}}")
    print("-" * (max_name_len + 2 + 8 + max_enrolment_len + 2))

    for student in app_data['students']:
        enrollment = ", ".join(student['enrolled_in'])
        print(f"{student['name']:<{max_name_len+2}}{student['id']:<8}{enrollment:<{max_enrolment_len+2}}")

#Main Function
#To show a menu interface for user to do decision
def main():
    load_data()

    while True:
        print("\n==== MSMS v2 (Persistent) ====")
        print("1. Register New Student")
        print("2. Check-in Student")
        print("3. Print Student Card")
        print("4. Listing Students or Teachers")
        print("5. Searching Students or Teachers")
        print("6. Admin-Only Features")
        print("q. Quit")

        choice = input("\nPlease enter your choice: ")

        made_change = False

        if choice == "1":
            name = input("Enter your student name: ")
            instrument = input("Enter the instrument you enrolled in: ")
            register_student(name,instrument)
            made_change = True
        
        elif choice == "2":
            id = input("Enter your id: ")
            course_id = input("Enter your course_id: ")
            check_in(id,course_id)
            made_change = True
        
        elif choice == "3":
            student_id = input("Enter your student id: ")
            find_student(student_id)
            print_student_card(student_id)
            made_change = True
            
        elif choice == "4":
            print("==== Listing Front Desk ====") #Listing teacher or student are assigned in one category as they are similar features
            print("1. List Teacher")
            print("2. List Student")
            choice_2 = input("Enter Your Choice: ")
            if choice_2 == "1": 
                list_teachers()
            if choice_2 == "2":
                list_students()
            made_change = True

        elif choice == "5":
            print("==== Searching Front Desk ====") #Searching teacher or student are assigned in one cateogot=ry as they are similar features
            print("1. Seacrh for teacher")
            print("2. Search for student")
            choice_2 = input("\nPlease enter your choice: ")
            if choice_2 == "1":
                term = input("\nPlease enter your choice: ")
                find_teacher(term)
            if choice_2 == "2":
                term = input("\nPlease enter your choice: ")
                find_student(term)

        elif choice == "6":
            password = input("Please enter your password: ") #Password is required while entering a admin only features
            """To determine that the one entering the features is a student or a teacher"""
            if check_password(password):
                validation = 2
            if check_student_password(password) and not check_password(password):
                validation = 1
            if not check_password(password) and not check_student_password(password):
                print("Wrong Password!")
                validation = False
            
            while validation == 1 or validation == 2:
                print("==== Admin Only Features ====")
                print("1. Update teacher and student info")
                print("2. Remove teacher and student")
                print("3. Add teacher")
                print("r. Return")

                choice_2 = input("\nEnter Your Choice: ")
                if choice_2 == "1":
                    print("==== Updating Front Desk=====")
                    print("1. Update Student Profile")
                    print("2. Update Teacher Profile")
                    choice_4 = input("\nPlese Enter Your Choice:")
                    if choice_4 == "1":
                            id = input("\nPlease enter your id: ")
                            if check_student_id(id):
                                find_student(id)
                                print("\n1. Name")
                                print("2. Enrolment")
                                print("3. Quit")
                                choice_3 = input("\nPlease enter your choice")
                                if choice_3 == "1":
                                    new_name = input("\nPlease enter a new name:")
                                    update_student(id, name=new_name)
                                elif choice_3 == "2":
                                    user_input = input("\nPlease enter your new enrolment seperated by comma and the old instrument should be included if you still want to enrol")
                                    new_enrolment = [i.strip() for i in user_input.split(",")]
                                    update_student(id, enrolled_in=new_enrolment )
                                elif choice_3 == "3":
                                    pass
                                else:
                                    print("Invalid Input!")
                    elif choice_4 == "2":
                        if validation == 1:
                            print("Error: Higher Permission is required for this functionality")
                            break
                        id = input("\nPlease enter your id: ")
                        if check_teacher_id(id):
                            find_teacher(id)
                            print("\n1. Name")
                            print("2. Specialty")
                            print("3. Quit")
                            choice_3 = input("\nPlease enter your choice")
                            if choice_3 == "1":
                                new_name = input("\nPlease enter a new name:")
                                update_teacher(id, name=new_name)
                            elif choice_3 == "2":
                                new_specialty = input("Please enter your new specialty")
                                update_teacher(id, specialty=new_specialty )
                            elif choice_3 == "3":
                                pass
                            else:
                                print("Invalid Input!")
                    else:
                        print("Invalid Input!")
                elif choice_2 == "2":
                    print("==== Removing Front Desk ====")
                    print("1. Remove Student")
                    print("2. Remove Teacher")
                    choice_4 = input("\nPlease enter your choice: ")
                    if validation == 1:
                        print("Error: Higher Permission is required for this functionality")
                        break
                    if choice_4 == "1":
                        id = input("\nEnter the student id: ")
                        if check_student_id(id):
                            find_student(id)
                            print("REMINDER: Please make sure this is the correct student profile to delete as it can't be recovered anymore!")
                            print("1. Yes")
                            print("2. No")
                            choice_3 = input("\nPlease enter your choice: ")
                            if choice_3 == "1":
                                remove_student(id)
                            elif choice_3 == "2":
                                pass
                            else:
                                print("Invalid Input!")
                    if choice_4 == "2":
                        id = input("\nEnter the teacher id: ")
                        if check_teacher_id(id):
                            find_teacher(id)
                            print("REMINDER: Please make sure this is the correct teacher profile to delete as it can't be recovered anymore!")
                            print("1. Yes")
                            print("2. No")
                            choice_3 = input("\nPlease enter your choice: ")
                            if choice_3 == "1":
                                remove_teacher(id)
                            elif choice_3 == "2":
                                pass
                            else:
                                print("Invalid Input!")
                    else:
                        print("Invalid Input!")
                elif choice_2 == "3":
                    if validation == 1:
                        print("Error: Higher Permission if required for this speciality")
                        break
                    name = input("\nEnter your name: ")
                    specialty = input("Enter your teaching specialty: ")
                    add_teacher(name,specialty)
                
                elif choice_2 == "r":
                    pass
                validation = False
            made_change = True

        elif choice.lower() == "q":
            print("Saving final changes and Exiting program. Goodbye!")
            made_change = True
            break

        else:
            print("Error: Invalid Choice.Please try again")
        
        if made_change:
            save_data()

if __name__ == "__main__":
    main()